-- PostgreSQL translation of the supplied legacy SQL.
-- Only dialect and source syntax corrections are applied. Do not extend these tables.

CREATE TABLE paises (
    numero integer NOT NULL,
    nombre varchar(250) NOT NULL,
    "nombreCorto" varchar(250),
    capital varchar(250) NOT NULL,
    nacionalidad varchar(250) NOT NULL,
    idiomas varchar(150) NOT NULL,
    CONSTRAINT pk_paises PRIMARY KEY (numero)
);

CREATE TABLE personas (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    documento varchar(20) NOT NULL,
    nombre varchar(150) NOT NULL,
    direccion varchar(250),
    estado varchar(15) CONSTRAINT "chkEstado" CHECK (estado IN ('activo', 'inactivo')),
    foto bytea,
    CONSTRAINT pk_personas PRIMARY KEY (identificador)
);

CREATE TABLE empleados (
    identificador integer NOT NULL,
    cargo varchar(100),
    sector integer,
    CONSTRAINT pk_empleados PRIMARY KEY (identificador)
);

CREATE TABLE sectores (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "nombreSector" varchar(150) NOT NULL,
    "codigoSector" varchar(10),
    "responsableSector" integer,
    CONSTRAINT pk_sectores PRIMARY KEY (identificador),
    CONSTRAINT fk_sectores_empleados FOREIGN KEY ("responsableSector") REFERENCES empleados (identificador)
);

CREATE TABLE seguros (
    "nroPoliza" varchar(30) NOT NULL,
    compania varchar(150) NOT NULL,
    "polizaCombinada" varchar(2) CONSTRAINT "chkpolizaCombinada" CHECK ("polizaCombinada" IN ('si', 'no')),
    importe decimal(18, 2) NOT NULL CONSTRAINT "chkImporte" CHECK (importe > 0),
    CONSTRAINT pk_seguro PRIMARY KEY ("nroPoliza")
);

CREATE TABLE clientes (
    identificador integer NOT NULL,
    "numeroPais" integer,
    admitido varchar(2) CONSTRAINT "chkAdmitido" CHECK (admitido IN ('si', 'no')),
    categoria varchar(10) CONSTRAINT "chkCategoria" CHECK (categoria IN ('comun', 'especial', 'plata', 'oro', 'platino')),
    verificador integer NOT NULL,
    CONSTRAINT pk_clientes PRIMARY KEY (identificador),
    CONSTRAINT fk_clientes_personas FOREIGN KEY (identificador) REFERENCES personas (identificador),
    CONSTRAINT fk_clientes_empleados FOREIGN KEY (verificador) REFERENCES empleados (identificador),
    CONSTRAINT fk_clientes_paises FOREIGN KEY ("numeroPais") REFERENCES paises (numero)
);

CREATE TABLE duenios (
    identificador integer NOT NULL,
    "numeroPais" integer,
    "verificacionFinanciera" varchar(2) CONSTRAINT "chkVF" CHECK ("verificacionFinanciera" IN ('si', 'no')),
    "verificacionJudicial" varchar(2) CONSTRAINT "chkVJ" CHECK ("verificacionJudicial" IN ('si', 'no')),
    "calificacionRiesgo" integer CONSTRAINT "chkCR" CHECK ("calificacionRiesgo" IN (1, 2, 3, 4, 5, 6)),
    verificador integer NOT NULL,
    CONSTRAINT pk_duenios PRIMARY KEY (identificador),
    CONSTRAINT fk_duenios_personas FOREIGN KEY (identificador) REFERENCES personas (identificador),
    CONSTRAINT fk_duenios_empleados FOREIGN KEY (verificador) REFERENCES empleados (identificador)
);

CREATE TABLE subastadores (
    identificador integer NOT NULL,
    matricula varchar(15),
    region varchar(50),
    CONSTRAINT pk_subastadores PRIMARY KEY (identificador),
    CONSTRAINT fk_subastadores_personas FOREIGN KEY (identificador) REFERENCES personas (identificador)
);

CREATE TABLE subastas (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha date CONSTRAINT "chkFecha" CHECK (fecha > CURRENT_DATE + 10),
    hora time NOT NULL,
    estado varchar(10) CONSTRAINT "chkES" CHECK (estado IN ('abierta', 'cerrada')),
    subastador integer,
    ubicacion varchar(350),
    "capacidadAsistentes" integer,
    "tieneDeposito" varchar(2) CONSTRAINT "chkTD" CHECK ("tieneDeposito" IN ('si', 'no')),
    "seguridadPropia" varchar(2) CONSTRAINT "chkSP" CHECK ("seguridadPropia" IN ('si', 'no')),
    categoria varchar(10) CONSTRAINT "chkCS" CHECK (categoria IN ('comun', 'especial', 'plata', 'oro', 'platino')),
    CONSTRAINT pk_subastas PRIMARY KEY (identificador),
    CONSTRAINT fk_subastas_subastadores FOREIGN KEY (subastador) REFERENCES subastadores (identificador)
);

CREATE TABLE productos (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    fecha date,
    disponible varchar(2) CONSTRAINT "chkD" CHECK (disponible IN ('si', 'no')),
    "descripcionCatalogo" varchar(500) DEFAULT 'No Posee',
    "descripcionCompleta" varchar(300) NOT NULL,
    revisor integer NOT NULL,
    duenio integer NOT NULL,
    seguro varchar(30),
    CONSTRAINT pk_productos PRIMARY KEY (identificador),
    CONSTRAINT fk_productos_empleados FOREIGN KEY (revisor) REFERENCES empleados (identificador),
    CONSTRAINT fk_productos_duenios FOREIGN KEY (duenio) REFERENCES duenios (identificador)
);

CREATE TABLE fotos (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    producto integer NOT NULL,
    foto bytea NOT NULL,
    CONSTRAINT pk_fotos PRIMARY KEY (identificador),
    CONSTRAINT fk_fotos_productos FOREIGN KEY (producto) REFERENCES productos (identificador)
);

CREATE TABLE catalogos (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    descripcion varchar(250) NOT NULL,
    subasta integer,
    responsable integer NOT NULL,
    CONSTRAINT pk_catalogos PRIMARY KEY (identificador),
    CONSTRAINT fk_catalogos_empleados FOREIGN KEY (responsable) REFERENCES empleados (identificador),
    CONSTRAINT fk_catalogos_subastas FOREIGN KEY (subasta) REFERENCES subastas (identificador)
);

CREATE TABLE "itemsCatalogo" (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    catalogo integer NOT NULL,
    producto integer NOT NULL,
    "precioBase" decimal(18, 2) NOT NULL CONSTRAINT "chkPB" CHECK ("precioBase" > 0.01),
    comision decimal(18, 2) NOT NULL CONSTRAINT "chkC" CHECK (comision > 0.01),
    subastado varchar(2) CONSTRAINT "chkS" CHECK (subastado IN ('si', 'no')),
    CONSTRAINT "pk_itemsCatalogo" PRIMARY KEY (identificador),
    CONSTRAINT "fk_itemsCatalogo_catalogos" FOREIGN KEY (catalogo) REFERENCES catalogos (identificador),
    CONSTRAINT "fk_itemsCatalogo_productos" FOREIGN KEY (producto) REFERENCES productos (identificador)
);

CREATE TABLE asistentes (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "numeroPostor" integer NOT NULL,
    cliente integer NOT NULL,
    subasta integer NOT NULL,
    CONSTRAINT pk_asistentes PRIMARY KEY (identificador),
    CONSTRAINT fk_asistentes_clientes FOREIGN KEY (cliente) REFERENCES clientes (identificador),
    CONSTRAINT fk_asistentes_subasta FOREIGN KEY (subasta) REFERENCES subastas (identificador)
);

CREATE TABLE pujos (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    asistente integer NOT NULL,
    item integer NOT NULL,
    importe decimal(18, 2) NOT NULL CONSTRAINT "chkI" CHECK (importe > 0.01),
    ganador varchar(2) DEFAULT 'no' CONSTRAINT "chkG" CHECK (ganador IN ('si', 'no')),
    CONSTRAINT pk_pujos PRIMARY KEY (identificador),
    CONSTRAINT fk_pujos_asistentes FOREIGN KEY (asistente) REFERENCES asistentes (identificador),
    CONSTRAINT "fk_pujos_itemsCatalogo" FOREIGN KEY (item) REFERENCES "itemsCatalogo" (identificador)
);

CREATE TABLE "registroDeSubasta" (
    identificador integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    subasta integer NOT NULL,
    duenio integer NOT NULL,
    producto integer NOT NULL,
    cliente integer NOT NULL,
    importe decimal(18, 2) NOT NULL CONSTRAINT "chkImportePagado" CHECK (importe > 0.01),
    comision decimal(18, 2) NOT NULL CONSTRAINT "chkComisionPagada" CHECK (comision > 0.01),
    CONSTRAINT "pk_registroDeSubasta" PRIMARY KEY (identificador),
    CONSTRAINT "fk_registroDeSubasta_subastas" FOREIGN KEY (subasta) REFERENCES subastas (identificador),
    CONSTRAINT "fk_registroDeSubasta_duenios" FOREIGN KEY (duenio) REFERENCES duenios (identificador),
    CONSTRAINT "fk_registroDeSubasta_producto" FOREIGN KEY (producto) REFERENCES productos (identificador),
    CONSTRAINT "fk_registroDeSubasta_cliente" FOREIGN KEY (cliente) REFERENCES clientes (identificador)
);
