DROP ALL OBJECTS;

CREATE TABLE paises (
    numero integer PRIMARY KEY,
    nombre varchar(250) NOT NULL,
    "nombreCorto" varchar(250),
    capital varchar(250),
    nacionalidad varchar(250)
);

CREATE TABLE personas (
    identificador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    documento varchar(20) NOT NULL,
    nombre varchar(150) NOT NULL,
    direccion varchar(250),
    estado varchar(15)
);

CREATE TABLE clientes (
    identificador integer PRIMARY KEY,
    "numeroPais" integer,
    admitido varchar(2),
    categoria varchar(10),
    verificador integer NOT NULL
);

CREATE TABLE empleados (
    identificador integer PRIMARY KEY,
    cargo varchar(100),
    sector integer
);

CREATE TABLE seguros (
    "nroPoliza" varchar(30) PRIMARY KEY,
    compania varchar(150) NOT NULL,
    "polizaCombinada" varchar(2),
    importe decimal(18,2) NOT NULL
);

CREATE TABLE duenios (
    identificador integer PRIMARY KEY,
    "numeroPais" integer,
    "verificacionFinanciera" varchar(2),
    "verificacionJudicial" varchar(2),
    "calificacionRiesgo" integer,
    verificador integer NOT NULL
);

CREATE TABLE subastadores (
    identificador integer PRIMARY KEY,
    matricula varchar(50) NOT NULL,
    region varchar(120)
);

CREATE TABLE subastas (
    identificador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date NOT NULL,
    hora time NOT NULL,
    estado varchar(10),
    subastador integer,
    ubicacion varchar(350),
    categoria varchar(10)
);

CREATE TABLE productos (
    identificador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha date,
    disponible varchar(2),
    "descripcionCatalogo" varchar(500),
    "descripcionCompleta" varchar(300),
    revisor integer,
    duenio integer,
    seguro varchar(30)
);

CREATE TABLE fotos (
    identificador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    producto integer NOT NULL,
    foto binary varying NOT NULL
);

CREATE TABLE catalogos (
    identificador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descripcion varchar(250) NOT NULL,
    subasta integer,
    responsable integer
);

CREATE TABLE "itemsCatalogo" (
    identificador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    catalogo integer NOT NULL,
    producto integer NOT NULL,
    "precioBase" decimal(18,2) NOT NULL,
    comision decimal(18,2) NOT NULL,
    subastado varchar(2)
);

CREATE TABLE asistentes (
    identificador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "numeroPostor" integer NOT NULL,
    cliente integer NOT NULL,
    subasta integer NOT NULL
);

CREATE TABLE pujos (
    identificador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    asistente integer NOT NULL,
    item integer NOT NULL,
    importe decimal(18,2) NOT NULL,
    ganador varchar(2) DEFAULT 'no'
);

CREATE TABLE "registroDeSubasta" (
    identificador integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subasta integer NOT NULL,
    duenio integer NOT NULL,
    producto integer NOT NULL,
    cliente integer NOT NULL,
    importe decimal(18,2) NOT NULL,
    comision decimal(18,2) NOT NULL
);

CREATE TABLE app_archivos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_cuenta_id bigint,
    tipo_contexto varchar(50) NOT NULL,
    filename_original varchar(255) NOT NULL,
    content_type varchar(100) NOT NULL,
    size_bytes bigint NOT NULL,
    storage_path varchar(500) NOT NULL,
    checksum varchar(128) NOT NULL,
    content_bytes varbinary,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_documentos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo varchar(60) NOT NULL,
    referencia_tipo varchar(50) NOT NULL,
    referencia_id bigint NOT NULL,
    archivo_id bigint NOT NULL,
    estado varchar(30) NOT NULL DEFAULT 'disponible',
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_solicitudes_registro (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(320) NOT NULL,
    nombre varchar(150) NOT NULL,
    apellido varchar(150) NOT NULL,
    domicilio_legal varchar(250) NOT NULL,
    id_pais_origen integer NOT NULL,
    foto_frente_dni_archivo_id bigint,
    foto_dorso_dni_archivo_id bigint,
    estado varchar(40) NOT NULL,
    setup_token_hash varchar(128),
    setup_token_expires_at timestamp with time zone,
    setup_token_used_at timestamp with time zone,
    motivo_rechazo varchar(500),
    persona_id integer,
    cliente_id integer,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_activity_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_cuentas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    persona_id integer NOT NULL UNIQUE,
    cliente_id integer NOT NULL UNIQUE,
    email varchar(320) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    estado varchar(40) NOT NULL,
    puntos integer NOT NULL DEFAULT 0,
    categoria_calculada varchar(10) NOT NULL,
    ultimo_acceso_at timestamp with time zone,
    intentos_login integer NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_refresh_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL,
    token_hash varchar(128) NOT NULL UNIQUE,
    expires_at timestamp with time zone NOT NULL,
    revoked_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_password_reset_tokens (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL,
    token_hash varchar(128) NOT NULL UNIQUE,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_auditoria (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_tipo varchar(20) NOT NULL,
    actor_id bigint,
    accion varchar(100) NOT NULL,
    entidad_tipo varchar(80) NOT NULL,
    entidad_id bigint,
    metadata_json text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_categoria_puntos (
    categoria varchar(10) PRIMARY KEY,
    puntos_minimos integer NOT NULL,
    orden integer NOT NULL
);

CREATE TABLE app_movimientos_puntos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL,
    delta integer NOT NULL,
    motivo varchar(100) NOT NULL,
    referencia_tipo varchar(50),
    referencia_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_medios_pago (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL,
    tipo varchar(30) NOT NULL,
    moneda varchar(3) NOT NULL,
    estado varchar(30) NOT NULL,
    principal boolean NOT NULL DEFAULT false,
    nacional boolean NOT NULL,
    alias_visible varchar(100),
    ultimos_4 varchar(4),
    titular varchar(200) NOT NULL,
    hash_identificador varchar(128) NOT NULL,
    limite_monto decimal(18,2),
    consumo_actual decimal(18,2) NOT NULL DEFAULT 0,
    saldo_garantia decimal(18,2),
    verificado_hasta timestamp with time zone,
    verificado_por_empleado_id integer,
    motivo_rechazo varchar(500),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

CREATE TABLE app_tarjetas (
    medio_pago_id bigint PRIMARY KEY,
    marca varchar(50),
    vencimiento_mes smallint NOT NULL,
    vencimiento_anio smallint NOT NULL
);

CREATE TABLE app_cuentas_bancarias (
    medio_pago_id bigint PRIMARY KEY,
    numero_cuenta_hash varchar(128),
    cbu_cvu_hash varchar(128),
    nombre_banco varchar(150) NOT NULL,
    alias varchar(100)
);

CREATE TABLE app_cheques_certificados (
    medio_pago_id bigint PRIMARY KEY,
    numero_cheque_hash varchar(128) NOT NULL,
    monto decimal(18,2) NOT NULL,
    fecha_vencimiento date NOT NULL,
    banco_emisor varchar(150) NOT NULL,
    foto_anverso_archivo_id bigint NOT NULL,
    foto_reverso_archivo_id bigint NOT NULL
);

CREATE TABLE app_inscripciones_subasta (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subasta_id integer NOT NULL,
    cuenta_id bigint NOT NULL,
    medio_pago_id bigint NOT NULL,
    estado varchar(30) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_subasta_ext (
    subasta_id integer PRIMARY KEY,
    titulo varchar(200) NOT NULL,
    descripcion varchar(1000),
    moneda varchar(3) NOT NULL,
    segmento varchar(100),
    estado_operativo varchar(30) NOT NULL,
    permite_inscripcion_online boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_subasta_estado_vivo (
    subasta_id integer PRIMARY KEY,
    item_catalogo_activo_id integer,
    version bigint NOT NULL DEFAULT 0,
    usuarios_conectados integer NOT NULL DEFAULT 0,
    lote_iniciado_at timestamp with time zone,
    lote_finaliza_estimado_at timestamp with time zone,
    retencion_hasta timestamp with time zone,
    proximo_lote_programado_at timestamp with time zone,
    subasta_finaliza_programado_at timestamp with time zone,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_pujas_live (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pujo_legacy_id integer,
    subasta_id integer NOT NULL,
    item_catalogo_id integer NOT NULL,
    cuenta_id bigint NOT NULL,
    medio_pago_id bigint NOT NULL,
    monto decimal(18,2) NOT NULL,
    moneda varchar(3) NOT NULL,
    estado varchar(30) NOT NULL,
    secuencia bigint NOT NULL,
    version_estado bigint NOT NULL,
    idempotency_key varchar(100) NOT NULL UNIQUE,
    motivo_rechazo varchar(500),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    confirmed_at timestamp with time zone
);

CREATE TABLE app_reservas_medio_pago (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medio_pago_id bigint NOT NULL,
    puja_id bigint NOT NULL UNIQUE,
    monto decimal(18,2) NOT NULL,
    estado varchar(20) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at timestamp with time zone,
    consumed_at timestamp with time zone
);

CREATE TABLE app_compras (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subasta_id integer NOT NULL,
    item_catalogo_id integer NOT NULL,
    producto_id integer NOT NULL,
    cuenta_comprador_id bigint,
    comprador_empresa boolean NOT NULL DEFAULT false,
    puja_id bigint,
    medio_pago_id bigint,
    monto_adjudicacion decimal(18,2) NOT NULL,
    moneda varchar(3) NOT NULL,
    estado varchar(50) NOT NULL,
    comision_comprador decimal(18,2) NOT NULL DEFAULT 0,
    comision_vendedor decimal(18,2) NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_multas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL,
    compra_id bigint NOT NULL,
    monto decimal(18,2) NOT NULL,
    moneda varchar(3) NOT NULL,
    porcentaje decimal(5,2) NOT NULL DEFAULT 10,
    estado varchar(20) NOT NULL,
    vence_at timestamp with time zone NOT NULL DEFAULT DATEADD('HOUR',72,CURRENT_TIMESTAMP),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at timestamp with time zone
);

CREATE TABLE app_pagos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id bigint,
    multa_id bigint,
    consignacion_devolucion_id bigint,
    medio_pago_id bigint NOT NULL,
    monto decimal(18,2) NOT NULL,
    moneda varchar(3) NOT NULL DEFAULT 'ARS',
    estado varchar(20) NOT NULL,
    referencia_externa varchar(150),
    idempotency_key varchar(100),
    error_codigo varchar(80),
    error_detalle varchar(500),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_notificaciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL,
    tipo varchar(60) NOT NULL,
    titulo varchar(200) NOT NULL,
    descripcion varchar(1000) NOT NULL,
    referencia_tipo varchar(50),
    referencia_id bigint,
    leida boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at timestamp with time zone
);

CREATE TABLE app_direcciones_envio (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL,
    alias varchar(80) NOT NULL,
    destinatario varchar(200) NOT NULL,
    calle varchar(200) NOT NULL,
    numero varchar(30) NOT NULL,
    piso varchar(30),
    codigo_postal varchar(20) NOT NULL,
    localidad varchar(120) NOT NULL,
    provincia varchar(120) NOT NULL,
    pais varchar(120) NOT NULL,
    telefono varchar(50),
    principal boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp with time zone
);

CREATE TABLE app_entregas (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compra_id bigint NOT NULL UNIQUE,
    tipo varchar(10) NOT NULL,
    direccion_envio_id bigint,
    costo_envio decimal(18,2) NOT NULL DEFAULT 0,
    estado varchar(30) NOT NULL,
    perdio_cobertura_seguro boolean NOT NULL DEFAULT false,
    direccion_snapshot_json text,
    direccion_snapshot_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_solicitudes_consignacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cuenta_id bigint NOT NULL,
    cliente_id integer NOT NULL,
    producto_id integer,
    item_catalogo_id integer,
    subasta_id integer,
    titulo varchar(200) NOT NULL,
    descripcion varchar(1000) NOT NULL,
    segmento varchar(80) NOT NULL DEFAULT 'general',
    categoria_sugerida varchar(10),
    historia text,
    historia_extendida text,
    artista_disenador varchar(250),
    fecha_objeto varchar(100),
    declaracion_propiedad boolean NOT NULL,
    acepta_devolucion_con_cargo boolean NOT NULL,
    estado varchar(50) NOT NULL,
    requiere_documentacion_origen boolean NOT NULL DEFAULT false,
    motivo_rechazo varchar(500),
    revisor_empleado_id integer,
    valor_base_propuesto decimal(18,2),
    moneda_propuesta varchar(3),
    comision_comprador_pct decimal(5,2),
    comision_vendedor_pct decimal(5,2),
    acuerdo_texto text,
    acuerdo_enviado_at timestamp with time zone,
    acuerdo_aceptado_at timestamp with time zone,
    acuerdo_rechazado_at timestamp with time zone,
    ubicacion_fisica varchar(350),
    idempotency_key varchar(100),
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_app_consignacion_account_idempotency UNIQUE (cuenta_id, idempotency_key)
);

CREATE TABLE app_consignacion_fotos (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL,
    archivo_id bigint NOT NULL,
    orden integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_consignacion_documentos_origen (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL,
    archivo_id bigint NOT NULL,
    estado varchar(20) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_consignacion_devoluciones (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL,
    motivo varchar(500) NOT NULL,
    costo decimal(18,2) NOT NULL,
    moneda varchar(3) NOT NULL,
    estado varchar(30) NOT NULL,
    pago_id bigint,
    modalidad varchar(10),
    direccion varchar(250),
    piso varchar(30),
    codigo_postal varchar(20),
    localidad varchar(120),
    provincia varchar(120),
    telefono_contacto varchar(50),
    direccion_envio_id bigint,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE app_liquidaciones_consignacion (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    solicitud_id bigint NOT NULL UNIQUE,
    compra_id bigint NOT NULL,
    monto_bruto decimal(18,2) NOT NULL,
    comision decimal(18,2) NOT NULL,
    monto_neto decimal(18,2) NOT NULL,
    cuenta_destino varchar(250) NOT NULL,
    estado varchar(20) NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    paid_at timestamp with time zone
);

INSERT INTO paises (numero, nombre, "nombreCorto", capital, nacionalidad) VALUES
    (32, 'Argentina', 'AR', 'Buenos Aires', 'argentina'),
    (76, 'Brasil', 'BR', 'Brasilia', 'brasileña'),
    (152, 'Chile', 'CL', 'Santiago', 'chilena'),
    (858, 'Uruguay', 'UY', 'Montevideo', 'uruguaya'),
    (840, 'Estados Unidos', 'US', 'Washington D.C.', 'estadounidense');

INSERT INTO personas (identificador, documento, nombre, direccion, estado) VALUES
    (2001, 'DNI-DEMO-APROBADO', 'Ana Aprobada', 'Av. Demo 100', 'activo'),
    (2002, 'DNI-DEMO-MULTA', 'Bruno Restringido', 'Av. Demo 200', 'activo'),
    (2003, 'DNI-DEMO-BLOQUEADO', 'Carla Bloqueada', 'Av. Demo 300', 'activo'),
    (2004, 'DNI-DEMO-ORO', 'Diego Oro', 'Av. Demo 400', 'activo'),
    (2100, 'EMPRESA-SUB-001', 'Martillero Demo', 'Casa central QuickBid', 'activo');

INSERT INTO clientes (identificador, "numeroPais", admitido, categoria, verificador) VALUES
    (2001, 32, 'si', 'plata', 1001),
    (2002, 32, 'si', 'especial', 1001),
    (2003, 32, 'si', 'comun', 1001),
    (2004, 32, 'si', 'oro', 1001);

INSERT INTO empleados (identificador,cargo) VALUES
    (1001,'Verificador de usuarios'),(1002,'Revisor de consignaciones'),(1004,'Responsable de catalogos');

INSERT INTO duenios (identificador,"numeroPais","verificacionFinanciera","verificacionJudicial","calificacionRiesgo",verificador)
VALUES (2004,32,'si','si',2,1002);

INSERT INTO subastadores (identificador,matricula,region) VALUES (2100,'MAT-DEMO-001','Buenos Aires');

INSERT INTO app_cuentas (
    id, persona_id, cliente_id, email, password_hash, estado,
    puntos, categoria_calculada, intentos_login
) VALUES
    (3001, 2001, 2001, 'aprobado@quickbid.demo',
     '$2a$10$V0pWYIdkIsrqbaS46NN5e.b88ECxrQ2of.z/qUHHT7rG.QHhRfJUm',
     'activa', 900, 'plata', 0),
    (3002, 2002, 2002, 'multa@quickbid.demo',
     '$2a$10$V0pWYIdkIsrqbaS46NN5e.b88ECxrQ2of.z/qUHHT7rG.QHhRfJUm',
     'restriccion_multa', 300, 'especial', 0),
    (3003, 2003, 2003, 'bloqueado@quickbid.demo',
     '$2a$10$V0pWYIdkIsrqbaS46NN5e.b88ECxrQ2of.z/qUHHT7rG.QHhRfJUm',
     'bloqueada_permanente', 0, 'comun', 0),
    (3004, 2004, 2004, 'oro@quickbid.demo',
     '$2a$10$V0pWYIdkIsrqbaS46NN5e.b88ECxrQ2of.z/qUHHT7rG.QHhRfJUm',
     'activa', 1800, 'oro', 0);

INSERT INTO app_categoria_puntos (categoria, puntos_minimos, orden) VALUES
    ('comun', 0, 1), ('especial', 250, 2), ('plata', 700, 3), ('oro', 1500, 4), ('platino', 3000, 5);

INSERT INTO app_medios_pago (id,cuenta_id,tipo,moneda,estado,principal,nacional,alias_visible,ultimos_4,titular,hash_identificador,limite_monto,consumo_actual,saldo_garantia,verificado_hasta) VALUES
    (5001,3001,'tarjeta','ARS','verificado',true,true,'Visa ARS terminada en 4242','4242','Ana Aprobada','demo-token-card-ars-aprobado',500000.00,25100.00,NULL,DATEADD('DAY',7,CURRENT_TIMESTAMP)),
    (5002,3001,'cuenta_bancaria','USD','verificado',true,false,'Cuenta USD demo',NULL,'Ana Aprobada','demo-token-bank-usd-aprobado',10000.00,0,NULL,DATEADD('DAY',7,CURRENT_TIMESTAMP)),
    (5003,3001,'cheque_certificado','ARS','pendiente_verificacion',false,true,'Cheque certificado pendiente',NULL,'Ana Aprobada','demo-token-cheque-ars-pendiente',NULL,0,150000.00,NULL),
    (5004,3002,'tarjeta','ARS','verificado',true,true,'Mastercard ARS restringida','4444','Bruno Restringido','demo-token-card-ars-multa',300000.00,150000.00,NULL,DATEADD('DAY',7,CURRENT_TIMESTAMP)),
    (5005,3002,'cuenta_bancaria','USD','verificado',false,false,'Cuenta USD eliminable',NULL,'Bruno Restringido','demo-token-bank-usd-multa',10000.00,0,NULL,DATEADD('DAY',7,CURRENT_TIMESTAMP)),
    (5006,3004,'cuenta_bancaria','ARS','verificado',true,true,'Cuenta ARS oro',NULL,'Diego Oro','demo-token-bank-ars-oro',1000000.00,0,NULL,DATEADD('DAY',7,CURRENT_TIMESTAMP));

INSERT INTO app_tarjetas (medio_pago_id,marca,vencimiento_mes,vencimiento_anio) VALUES (5001,'Visa',12,2030),(5004,'Mastercard',11,2030);
INSERT INTO app_cuentas_bancarias (medio_pago_id,numero_cuenta_hash,cbu_cvu_hash,nombre_banco,alias) VALUES (5002,'hash-account-usd','hash-cbu-usd','Banco Demo Exterior','ANA.USD'),(5005,'hash-account-multa','hash-cbu-multa','Banco Demo Exterior','BRUNO.USD'),(5006,'hash-account-oro','hash-cbu-oro','Banco Demo','DIEGO.ORO');
INSERT INTO app_cheques_certificados (medio_pago_id,numero_cheque_hash,monto,fecha_vencimiento,banco_emisor,foto_anverso_archivo_id,foto_reverso_archivo_id) VALUES (5003,'hash-cheque',150000.00,CURRENT_DATE+90,'Banco Demo',1,2);

INSERT INTO subastas (identificador,fecha,hora,estado,subastador,ubicacion,categoria) VALUES
    (6001,CURRENT_DATE+30,'18:00:00','abierta',2100,'Casa central QuickBid','plata'),
    (6002,CURRENT_DATE+45,'19:00:00','abierta',2100,'Casa central QuickBid','especial'),
    (6003,CURRENT_DATE+20,'17:00:00','cerrada',2100,'Casa central QuickBid','comun'),
    (6004,CURRENT_DATE+60,'20:00:00','abierta',2100,'Salon Oro QuickBid','oro');

INSERT INTO app_subasta_ext (subasta_id,titulo,descripcion,moneda,segmento,estado_operativo) VALUES
    (6001,'Diseno argentino en vivo','Subasta ARS con lote activo.','ARS','diseno','en_vivo'),
    (6002,'Coleccion internacional USD','Subasta futura en USD.','USD','coleccion','programada'),
    (6003,'Remate clasico finalizado','Subasta cerrada demo.','ARS','general','finalizada'),
    (6004,'Seleccion oro','Subasta categoria oro.','ARS','arte','abierta');

INSERT INTO productos (identificador,"descripcionCatalogo",duenio) VALUES
    (8001,'Sillon de diseno argentino',2004),(8002,'Juego de te de porcelana',2004),(8003,'Reloj internacional',2004),
    (8004,'Lampara clasica',2004),(8005,'Mesa restaurada',2004),(8007,'Obra seleccion oro',2004);
INSERT INTO fotos (identificador,producto,foto) VALUES (8101,8001,X'89504E470D0A1A0A'),(8102,8002,X'89504E470D0A1A0A'),(8103,8003,X'89504E470D0A1A0A');
INSERT INTO catalogos (identificador,descripcion,subasta) VALUES
    (7001,'Catalogo diseno',6001),(7002,'Catalogo internacional',6002),(7003,'Catalogo clasico',6003),(7004,'Catalogo oro',6004);
INSERT INTO "itemsCatalogo" (identificador,catalogo,producto,"precioBase",comision,subastado) VALUES
    (9001,7001,8001,20000,2000,'no'),(9002,7001,8002,35000,3500,'no'),(9003,7002,8003,1500,150,'no'),
    (9004,7003,8004,120000,12000,'si'),(9005,7003,8005,80000,8000,'si'),(9006,7004,8007,250000,25000,'no');
INSERT INTO app_subasta_estado_vivo (subasta_id,item_catalogo_activo_id,version,usuarios_conectados) VALUES
    (6001,9001,1,1),(6002,NULL,0,0),(6003,NULL,3,0),(6004,NULL,0,0);
INSERT INTO app_inscripciones_subasta (id,subasta_id,cuenta_id,medio_pago_id,estado) VALUES (10001,6001,3001,5001,'aprobada');
INSERT INTO asistentes (identificador,"numeroPostor",cliente,subasta) VALUES (11001,1,2001,6001);
INSERT INTO pujos (identificador,asistente,item,importe,ganador) VALUES (12001,11001,9001,25100.00,'no');

INSERT INTO app_pujas_live (id, pujo_legacy_id, subasta_id, item_catalogo_id, cuenta_id, medio_pago_id, monto, moneda, estado, secuencia, version_estado, idempotency_key) VALUES
    (12501, 12001, 6001, 9001, 3001, 5001, 25100.00, 'ARS', 'aceptada', 1, 1, 'demo-bid-live'),
    (12502, NULL, 6003, 9004, 3002, 5004, 150000.00, 'ARS', 'ganadora', 1, 1, 'demo-bid-fine'),
    (12503, NULL, 6003, 9005, 3001, 5001, 95000.00, 'ARS', 'ganadora', 2, 1, 'demo-bid-paid');

INSERT INTO app_reservas_medio_pago (id, medio_pago_id, puja_id, monto, estado) VALUES
    (12701, 5001, 12501, 25100.00, 'activa');

INSERT INTO app_compras (id, subasta_id, item_catalogo_id, producto_id, cuenta_comprador_id, medio_pago_id, monto_adjudicacion, moneda, estado, comision_comprador, comision_vendedor) VALUES
    (13001, 6003, 9004, 8004, 3002, 5004, 150000.00, 'ARS', 'multa_activa', 15000.00, 15000.00),
    (13002, 6003, 9005, 8005, 3001, 5001, 95000.00, 'ARS', 'pagos_extra_pendientes', 9500.00, 9500.00);

INSERT INTO app_multas (id,cuenta_id,compra_id,monto,moneda,porcentaje,estado,vence_at) VALUES
    (14001,3002,13001,15000.00,'ARS',10.00,'pendiente',DATEADD('HOUR',72,CURRENT_TIMESTAMP));

INSERT INTO app_pagos (id, compra_id, medio_pago_id, monto, estado) VALUES (15002, 13002, 5001, 95000.00, 'aprobado');

INSERT INTO app_notificaciones (id, cuenta_id, tipo, titulo, descripcion, referencia_tipo, referencia_id, leida) VALUES
    (18001, 3001, 'inscripcion_subasta', 'Inscripcion aprobada', 'Tu inscripcion fue aprobada.', 'subasta', 6001, false),
    (18002, 3001, 'puja_aceptada', 'Puja aceptada', 'Tu puja es la mejor oferta.', 'puja', 12501, false),
    (18003, 3002, 'multa_generada', 'Multa pendiente', 'Se genero una multa.', 'multa', 14001, false);

INSERT INTO app_direcciones_envio (id, cuenta_id, alias, destinatario, calle, numero, codigo_postal, localidad, provincia, pais, principal) VALUES
    (5101, 3001, 'Casa', 'Ana Aprobada', 'Av. Demo', '100', 'C1000', 'Buenos Aires', 'Buenos Aires', 'Argentina', true);

INSERT INTO app_solicitudes_consignacion (
    id,cuenta_id,cliente_id,producto_id,item_catalogo_id,subasta_id,titulo,descripcion,segmento,categoria_sugerida,
    historia,historia_extendida,artista_disenador,fecha_objeto,ubicacion_fisica,
    declaracion_propiedad,acepta_devolucion_con_cargo,estado,revisor_empleado_id,valor_base_propuesto,
    moneda_propuesta,comision_comprador_pct,comision_vendedor_pct
) VALUES
    (16001,3004,2004,NULL,NULL,NULL,'Vasija pendiente','Solicitud inicial demo','arte','comun',NULL,NULL,NULL,NULL,NULL,true,true,'pendiente_revision',NULL,NULL,NULL,NULL,NULL),
    (16002,3004,2004,NULL,NULL,NULL,'Cuadro documentado','Documentacion adicional demo','arte','especial',NULL,NULL,NULL,NULL,NULL,true,true,'documentacion_adicional',1002,NULL,NULL,NULL,NULL),
    (16007,3004,2004,8005,9005,6003,'Mesa restaurada vendida','Lista para liquidar','muebles','comun',
     'Mesa restaurada con procedencia particular.','Trabajo de restauracion documentado por el equipo de catalogacion.',
     'Taller de restauracion QuickBid','1970',STRINGDECODE('Dep\u00f3sito de custodia QuickBid, Buenos Aires'),
     true,true,'vendida',1002,80000,'ARS',10,10);
